# Generated by Django 4.1.5 on 2023-01-18 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=200)),
                ('description', models.CharField(blank=True, default='Project description', max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New task', max_length=200)),
                ('description', models.CharField(blank=True, default='Task description', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link1', models.IntegerField(blank=True, default=118, null=True)),
                ('link2', models.IntegerField(blank=True, default=150, null=True)),
                ('link3', models.IntegerField(blank=True, default=150, null=True)),
                ('link4', models.IntegerField(blank=True, default=0, null=True)),
                ('link5', models.IntegerField(blank=True, default=54, null=True)),
                ('link1_min', models.IntegerField(blank=True, default=-80, null=True)),
                ('link2_min', models.IntegerField(blank=True, default=5, null=True)),
                ('link3_min', models.IntegerField(blank=True, default=-115, null=True)),
                ('link4_min', models.IntegerField(blank=True, default=-85, null=True)),
                ('link5_min', models.IntegerField(blank=True, default=0, null=True)),
                ('link1_max', models.IntegerField(blank=True, default=80, null=True)),
                ('link2_max', models.IntegerField(blank=True, default=175, null=True)),
                ('link3_max', models.IntegerField(blank=True, default=55, null=True)),
                ('link4_max', models.IntegerField(blank=True, default=85, null=True)),
                ('link5_max', models.IntegerField(blank=True, default=0, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.project')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
