# Generated by Django 4.1.5 on 2023-02-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot', '0002_alter_robot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='New Project', max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='description',
            field=models.CharField(blank=True, default='Robot description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(default='New robot', max_length=50),
        ),
        migrations.CreateModel(
            name='InverseKinematics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IK Calculation', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('x', models.IntegerField(blank=True, default=0, null=True)),
                ('y', models.IntegerField(blank=True, default=0, null=True)),
                ('z', models.IntegerField(blank=True, default=0, null=True)),
                ('alpha', models.IntegerField(blank=True, default=0, null=True)),
                ('theta1', models.IntegerField(blank=True, default=0, null=True)),
                ('theta2', models.IntegerField(blank=True, default=0, null=True)),
                ('theta3', models.IntegerField(blank=True, default=0, null=True)),
                ('theta4', models.IntegerField(blank=True, default=0, null=True)),
                ('theta11', models.IntegerField(blank=True, default=0, null=True)),
                ('theta22', models.IntegerField(blank=True, default=0, null=True)),
                ('theta33', models.IntegerField(blank=True, default=0, null=True)),
                ('theta44', models.IntegerField(blank=True, default=0, null=True)),
                ('Robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robot.robot')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForwardKinematics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FK Calculation', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('theta1', models.IntegerField(blank=True, default=0, null=True)),
                ('theta2', models.IntegerField(blank=True, default=0, null=True)),
                ('theta3', models.IntegerField(blank=True, default=0, null=True)),
                ('theta4', models.IntegerField(blank=True, default=0, null=True)),
                ('x', models.IntegerField(blank=True, default=0, null=True)),
                ('y', models.IntegerField(blank=True, default=0, null=True)),
                ('z', models.IntegerField(blank=True, default=0, null=True)),
                ('Robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robot.robot')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
