# Generated by Django 4.1.5 on 2023-02-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_alter_project_name_alter_robot_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardkinematics',
            name='alpha',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='modified',
            field=models.DateTimeField(blank=True, default='2023-12-12 12:12', null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='theta1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='theta2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='theta3',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='theta4',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='x',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='y',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='z',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='modified',
            field=models.DateTimeField(blank=True, default='2023-12-12 12:12', null=True),
        ),
    ]
