# Generated by Django 4.1.5 on 2023-04-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_forwardkinematics_alpha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardkinematics',
            name='Robot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fk_calc', to='robot.robot'),
        ),
        migrations.AlterField(
            model_name='forwardkinematics',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='Robot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ik_calc', to='robot.robot'),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta11',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta22',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta3',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta33',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta4',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='inversekinematics',
            name='theta44',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='robot.project'),
        ),
    ]
